### ISSUE TITLE
Wonderful job, waiting for the code!

### ISSUE THREAD

**Issue by Anikily** [LaoYang1994/SOGNet#1]

**Comment by LaoYang1994** [comment]
Thanks for your attention. We are moving the code to detectron2 and the code will be released soon.

**Comment by SkeletonOne** [comment]
@LaoYang1994 How is everything going? Looking forward to it.

**Comment by LaoYang1994** [comment]
@SkeletonOne Hi, the code for sognet has been released. But there are some bugs in the detectron2 version code. We will release the d2-version code as soon as possible.

**Comment by SkeletonOne** [comment]
@LaoYang1994 Cool! Thanks for your work!
