### ISSUE TITLE
how to test on my own images?

### ISSUE THREAD

**Issue by squashking** [LaoYang1994/SOGNet#5]
Hi, could you give me some instructions on how to test on my own images?
Thanks a lot!

**Comment by LaoYang1994** [comment]
@squashking Hi, I'm sorry to tell you that we don't provide a interface for testing a single image. But you can format your data like coco and replace "val2017" in https://github.com/LaoYang1994/SOGNet/blob/2fe6d32fe40f2ebbc2ff4c3ad1aafb40c83a75d1/configs/sognet_r50_coco_4gpu_novoid.yaml#L14 with your own data.

**Comment by squashking** [comment]
if I don't have ground truth annotations for my own images, can I test them? If yes, how to save the panoptic segmentation as images? Thanks.
